apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-db
  template:
    metadata:
      labels:
        app: customer-db
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: customerdb
          ports:
            - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: customer-db
spec:
  selector:
    app: customer-db
  ports:
    - port: 3306
      targetPort: 3306


