apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: customer-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: customer-config
            - secretRef:
                name: customer-secret

---

apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - port: 8080
      targetPort: 8080


