name: ci with integrationtests

on:
  push:
     branches: [master]

#  schedule:
 #   - cron: "0 3 * * *" #Varje natt kl 03

jobs:
  yahyastester:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: customerdb

        ports:
          - 3306:3306
        options:
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10




    steps:
 #     - name: Starta hela systemet
  #      run: docker compose up -d --build

   #   - name: vänta på att allt ska startas
    #    run: sleep 30

     # - name: test mot vår endpoint i customer-service
      #  run: curl -f http://localhost:8080/customer/1


     # - name: Checka ut koden
     #   uses: actions/checkout@v4

      - name: Sätt upp java matrix
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: bygg och kör tester
        run: mvn test



#      - name: stänga ner allt
 #       if: always()
  #      run: docker compose down -v



        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/${{secrets.DATABASE_NAME}}
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
