name: ci with integrationtests

on:
  push:
     branches: [master]

#  schedule:
 #   - cron: "0 3 * * *" #Varje natt kl 03

jobs:
  yahyastester:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: customerdb

        ports:
          - 3306:3306
        options:
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10


    steps:

      - name: Checka ut koden
        uses: actions/checkout@v4

      - name: Sätt upp java matrix
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: bygg och kör tester
        run: mvn test


      - name: Logga in på dockerhub
        run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "yahyasystementor" --password-stdin


      - name: Bygg image
        run: |
          docker build -t yahyasystementor/customer-service:${{github.run_number}} .

      - name: Pusha till dockerhub
        run: |
          docker push yahyasystementor/customer-service:${{github.run_number}}



        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/customerdb
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
