name: ci with integrationtests

on:
  push:
     branches: [master]

#  schedule:
 #   - cron: "0 3 * * *" #Varje natt kl 03

jobs:
  yahyastester:
    runs-on: ubuntu-latest

    steps:

      - name: Checka ut koden
        uses: actions/checkout@v4

      - name: Sätt upp java matrix
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: bygg och kör tester
        run: mvn test

      - name: Logga in på dockerhub
        run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "yahyasystementor" --password-stdin


      - name: Bygg image
        run: |
          docker build -t yahyasystementor/customer-service:2.0

      - name: Pusha till dockerhub
        run: |
          docker push yahyasystementor/customer-service:2.0
